git:
  paths:
    - C:\projects\chg-fox-monolith2
    - C:\projects\sts
filesystem:
  paths:
    - c:\projects\sts
    - C:\Users\kirobins\OneDrive - CHG Healthcare\Documents\obsidian-todo
    - c:\projects\chg-ldm-doc
    - C:\projects\claude-sandbox-mcps-etc
desktop-commander:
  paths:
    - C:/projects/sts
n8n:
  api_url: " http://host.docker.internal:5678"
database-server:
  database_url: postgresql+asyncpg://postgres:root@localhost:5432/postgres
